main:
	g++ leitor.cpp -o leitor-app -lsfml-graphics -lsfml-window -lsfml-system -std=c++14 -Wall -O3
	g++ escritor.cpp -o escritor-app -lsfml-graphics -lsfml-window -lsfml-system -std=c++14 -Wall -O3
